//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_AppWPF.EF
{
    using System;
    using System.Collections.Generic;
    

    public partial class Tour
    {
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDAgent { get; set; }
        public int IDTypeTour { get; set; }
        public int IDCountry { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public int IDAirline { get; set; }
        public Nullable<int> IDHotel { get; set; }
        public int IDCountTourist { get; set; }


        public string CLIENT { get => $"{Client.LastName} {Client.FirstName} {Client.Patronymic}"; }
        public string AGENT { get => $"{Agent.LastName} {Agent.FirstName} {Agent.Patronymic}"; }
        public string TYPETOUR { get => $"{TypeTour.Name}"; }
        public string COUNTRY { get => $"{Country.Name}"; }
        public string AIRLANE { get => $"{Airline.Name}"; }
        public string HOTEL { get => $"{Hotel.Name}"; }
        public string COUNTTOURIST { get => $"{CountTourist.Count}"; }

        public virtual Agent Agent { get; set; }
        public virtual Airline Airline { get; set; }
        public virtual Client Client { get; set; }
        public virtual Country Country { get; set; }
        public virtual CountTourist CountTourist { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual TypeTour TypeTour { get; set; }
    }
}
